### ISSUE TITLE
Error when initializing renderers?

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#220]
lib@1.7.0, npm@1.7.0, xp@7.7.0

```
2021-06-16 13:20:03,206 INFO  c.e.l.r.ssr.ServerSideRenderer - Setting up SSR with 8 engines...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#4: starting init...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#6: starting init...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#3: starting init...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#7: starting init...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#8: starting init...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#1: starting init...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#5: starting init...
2021-06-16 13:20:03,284 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#2: starting init...
2021-06-16 13:20:03,284 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,284 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,284 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,284 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,285 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,285 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,285 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,285 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:03,294 INFO  c.e.l.r.s.e.EngineFactory - #3: loading polyfill basics
2021-06-16 13:20:03,294 INFO  c.e.l.r.s.e.EngineFactory - #6: loading polyfill basics
2021-06-16 13:20:03,294 INFO  c.e.l.r.s.e.EngineFactory - #1: loading polyfill basics
2021-06-16 13:20:03,294 INFO  c.e.l.r.s.e.EngineFactory - #5: loading polyfill basics
2021-06-16 13:20:03,294 INFO  c.e.l.r.s.e.EngineFactory - #7: loading polyfill basics
2021-06-16 13:20:03,294 INFO  c.e.l.r.s.e.EngineFactory - #4: loading polyfill basics
2021-06-16 13:20:03,294 INFO  c.e.l.r.s.e.EngineFactory - #2: loading polyfill basics
2021-06-16 13:20:03,295 INFO  c.e.l.r.s.e.EngineFactory - #8: loading polyfill basics
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#3: destroyed.
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#4: destroyed.
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#6: destroyed.
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#7: destroyed.
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#1: destroyed.
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#2: destroyed.
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#5: destroyed.
2021-06-16 13:20:03,295 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#8: destroyed.
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#3
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#8
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#6
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#2
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#5
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#7
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#1
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#4
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer$AsyncPoolRendererInitializer.run(ServerSideRenderer.java:112)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 6 more
2021-06-16 13:20:04,176 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#10: starting init...
2021-06-16 13:20:04,176 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#9: starting init...
2021-06-16 13:20:04,176 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:04,176 INFO  c.e.l.r.s.e.EngineBuilderUncached - Init SSR engine: no settings, uncached
2021-06-16 13:20:04,176 INFO  c.e.l.r.s.e.EngineFactory - #9: loading polyfill basics
2021-06-16 13:20:04,176 INFO  c.e.l.r.s.e.EngineFactory - #10: loading polyfill basics
2021-06-16 13:20:04,176 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#9: destroyed.
2021-06-16 13:20:04,176 INFO  c.e.lib.react4xp.ssr.pool.Renderer - Renderer#10: destroyed.
2021-06-16 13:20:04,366 ERROR c.e.l.r.ssr.ServerSideRenderer - com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#9
com.enonic.lib.react4xp.ssr.errors.RenderException: Couldn't init Renderer#9
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:68)
	at com.enonic.lib.react4xp.ssr.pool.RendererFactory.makeObject(RendererFactory.java:31)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232)
	at com.enonic.lib.react4xp.ssr.ServerSideRenderer.render(ServerSideRenderer.java:140)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$195$8534A$index.L:1#React4xp#React4xp#L:136(de.osde.react4xp2test:/lib/enonic/react4xp/index.js:140)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$194$26656AAA$index.L:1#React4xp#renderSSRIntoContainer(de.osde.react4xp2test:/lib/enonic/react4xp/index.js:473)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$193$9030A$index.L:1#React4xp#React4xp#L:154(de.osde.react4xp2test:/lib/enonic/react4xp/index.js:164)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$180$27874AAAA$index.L:1#L:517(de.osde.react4xp2test:/lib/enonic/react4xp/index.js:541)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$177$646A$default.L:1#get(de.osde.react4xp2test:/site/pages/default/default.js:23)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:120)
	at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:36)
	at com.enonic.xp.script.impl.executor.ScriptExportsImpl.executeMethod(ScriptExportsImpl.java:59)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.doExecute(ControllerScriptImpl.java:71)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.lambda$execute$0(ControllerScriptImpl.java:36)
	at com.enonic.xp.trace.Tracer.traceEx(Tracer.java:72)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:51)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:98)
	at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.execute(ControllerScriptImpl.java:36)
	at com.enonic.xp.portal.impl.rendering.PageRenderer.doRender(PageRenderer.java:49)
	at com.enonic.xp.portal.impl.rendering.PageRenderer.doRender(PageRenderer.java:28)
	at com.enonic.xp.portal.impl.rendering.PostProcessingRenderer.render(PostProcessingRenderer.java:25)
	at com.enonic.xp.portal.impl.rendering.RendererDelegateImpl.lambda$render$1(RendererDelegateImpl.java:40)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.enonic.xp.portal.impl.rendering.RendererDelegateImpl.render(RendererDelegateImpl.java:40)
	at com.enonic.xp.portal.impl.handler.render.PageHandlerWorker.execute(PageHandlerWorker.java:127)
	at com.enonic.xp.portal.impl.handler.render.PageHandler.doHandle(PageHandler.java:62)
	at com.enonic.xp.portal.impl.handler.render.PageHandler.doHandle(PageHandler.java:22)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.portal.handler.BasePortalHandler.doHandle(BasePortalHandler.java:46)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.impl.trace.TraceWebFilter.doHandle(TraceWebFilter.java:38)
	at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
	at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:30)
	at com.enonic.xp.web.impl.handler.WebDispatcherImpl.dispatch(WebDispatcherImpl.java:44)
	at com.enonic.xp.web.impl.handler.WebDispatcherServlet.doHandle(WebDispatcherServlet.java:142)
	at com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:40)
	at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:38)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:51)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
	at com.enonic.xp.portal.impl.idprovider.IdProviderFilter.doHandle(IdProviderFilter.java:46)
	at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
	at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
	at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
	at com.enonic.xp.web.impl.context.ContextFilter.lambda$doHandle$0(ContextFilter.java:34)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:102)
	at com.enonic.xp.web.impl.context.ContextFilter.doHandle(ContextFilter.java:33)
	at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
	at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
	at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
	at com.enonic.xp.web.vhost.impl.VirtualHostFilter.doHandle(VirtualHostFilter.java:73)
	at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
	at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
	at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
	at com.enonic.xp.web.impl.dos.DosFilterWrapper.doFilter(DosFilterWrapper.java:65)
	at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
	at org.eclipse.jetty.servlets.HeaderFilter.doFilter(HeaderFilter.java:117)
	at com.enonic.xp.web.impl.header.HeaderFilterWrapper.doHandle(HeaderFilterWrapper.java:51)
	at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
	at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
	at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
	at com.enonic.xp.web.impl.dispatch.pipeline.FilterPipelineImpl.filter(FilterPipelineImpl.java:37)
	at com.enonic.xp.web.impl.dispatch.DispatchServletImpl.service(DispatchServletImpl.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:713)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at com.enonic.lib.react4xp.ssr.pool.Renderer.evalAndGetByKey(Renderer.java:117)
	at com.enonic.lib.react4xp.ssr.engineFactory.EngineFactory.buildEngine(EngineFactory.java:102)
	at com.enonic.lib.react4xp.ssr.pool.Renderer.<init>(Renderer.java:51)
	... 143 more
```

**Comment by espen42** [comment]
For both the most recent react4xp versions (ie. recommended lib+npm version combinations), it appears the `engine` object is `null` after `NashornScriptEngine engine = engineBuilder.buildEngine();` in https://github.com/enonic/lib-react4xp/blob/master/src/main/java/com/enonic/lib/react4xp/ssr/engineFactory/EngineFactory.java#L95

This happns **in XP 7.7 but not XP 7.6**. Related to different java versions?
