### ISSUE TITLE
React.render fails when body parameter contains non-breaking space HTML entities

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#37]
If an HTML string (with a target container for the react entry) contains `&nbsp;` and is used as the `body` parameter in a `React4xp.render` call with server-side rendering, it fails with the message:

```
Returning the submitted body unchanged.
org.jdom2.input.JDOMParseException: Error on line 158: The entity "nbsp" was referenced, but not declared.
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
        at com.enonic.lib.react4xp.HtmlInserter.insertInsideContainer(HtmlInserter.java:73)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$369696$15653AA$index.L:1#React4xp#renderTargetContainer(mimir:/lib/enonic/react4xp/index.js:291)
```

**Comment by rymsha** [comment]
https://github.com/enonic/lib-react4xp/pull/679 fixes it
